if(screen.width <= '800'){
	document.write("<style>#main_table{background:url('http:/http://legendbattles.ru/images.twilight-war.ru/index/background/800.jpg') center top no-repeat;}</style>");
}else if(screen.width <= '1024'){
	document.write("<style>#main_table{background:url('http:/http://legendbattles.ru/images.twilight-war.ru/index/background/1024.jpg') center top no-repeat;}</style>");
}else if(screen.width <= '1024'){
	document.write("<style>#main_table{background:url('http:/http://legendbattles.ru/images.twilight-war.ru/index/background/1024.jpg') center top no-repeat;}</style>");
}else if(screen.width <= '1152'){
	document.write("<style>#main_table{background:url('http:/http://legendbattles.ru/images.twilight-war.ru/index/background/1152.jpg') center top no-repeat;}</style>");
}else if(screen.width <= '1280'){
	document.write("<style>#main_table{background:url('http:/http://legendbattles.ru/images.twilight-war.ru/index/background/1280.jpg') center top no-repeat;}</style>");
}else if(screen.width > '1280'){
	document.write("<style>#main_table{background:url('http:/http://legendbattles.ru/images.twilight-war.ru/index/background/1500.jpg') center top no-repeat;}</style>");
}

ShowPage = function(module_id,size){
    $.nyroModalManual({url: '/'+module_id+'.php', width:size});
}

viewpage = function(){
	document.write('<table border="0" cellpadding="0" cellspacing="0" width="100%" height="100%" id="main_table">  <tr>    <td width="40" height="40"><img src="http:/http://legendbattles.ru/images.twilight-war.ru/index/t_l.gif" /></td>    <td style="background:url(http:/http://legendbattles.ru/images.twilight-war.ru/index/t_c.jpg);"><div id="authorization" class="p_elem">      <table>        <tr>          <td class="td_side">&nbsp;</td>          <td><div id="auth_center" class="div_center">            <form method="post" id="auth_form" action="./game.php">              <table class="tbl_center">                <tr>                  <td><div id="auth_title"></div>                    <div id="auth_login">                      <input onfocus="if(this.value == \'Логин\') this.value  = \'\';" onblur="if(this.value == \'\') this.value = \'Логин\';" type="text" name="player_nick" value="Логин">                    </div>                    <div id="auth_pass">                      <input id="temp" onfocus="this.style.display = \'none\'; getElementById(\'real\').style.display = \'inline\'; getElementById(\'real\').focus();" type="text" name="temp" value="Пароль">                      <input style="display:none" id="real" onblur="if(this.value == \'\') {getElementById(\'temp\').style.display = \'inline\'; this.style.display = \'none\';}" type="password" name="player_password" value="">                    </div>                    <div id="auth_logon"><a href="javascript://" onclick="document.getElementById(\'auth_form\').submit()" ></a></div>                </tr>              </table>              <input type="submit" style="height:0; width:0; overflow:hidden; position:absolute;">            </form>          </div></td>          <td class="td_side">&nbsp;</td>        </tr>      </table>    </div></td>    <td width="40" height="40"><img src="http:/http://legendbattles.ru/images.twilight-war.ru/index/t_r.gif" /></td>  </tr>  <tr>    <td style="background:url(http:/http://legendbattles.ru/images.twilight-war.ru/index/l.gif);"></td>    <td>&nbsp;</td>    <td style="background:url(http:/http://legendbattles.ru/images.twilight-war.ru/index/r.gif);"></td>  </tr>  <tr>    <td width="40" height="81"><img src="http:/http://legendbattles.ru/images.twilight-war.ru/index/b_l.gosters" /></td>    <td style="background:url(http:/http://legendbattles.ru/images.twilight-war.ru/index/b_c.gif);" align="center">&nbsp;</td>    <td width="40" height="81"><img src="http:/http://legendbattles.ru/images.twilight-war.ru/index/b_r.gif" /></td>  </tr></table><div id="dragons">  <div id="l_dragon"></div>  <div id="r_dragon"></div></div><div id="menu"><img src="http:/http://legendbattles.ru/images.twilight-war.ru/index/menu.png"></div><div id="navig"><b><a href="#" onClick="ShowPage(\'newreg\',\'380\');">Регистрация11</a></b> | <b><a href="http://forum.twilight-war.ru">Форум</a></b> | <b><a href="#">Забыли пароль?</a></b></div>');	
}