var d = document;
var el,param,table,buy,priv,seif,auto,smiles;
var names = new Array ('Базовый','Premuim','Gold','VIP','<font color="#FF9911">Platinum</font>');
var img = new Array ('base_big.gif','premium_big.gif','gold_big.gif','vip_big.gif','p5.png');
priv = new Array('нет.','Простое разрешение мэрии (позволяет выходить из города в ночное время)','Разрешение мэрии для VIP-персоны(позволяет входить и выходить из города в ночное время).');
seif = new Array('нет.','30 дней.')
auto = new Array('нет.','Да.')
smiles = new Array('нет.','Да.')
writeinfo = function(e){
	el = d.getElementById('prem_info');
	buy = ( price[e][0] > 0 ? (dlr >= price[e][0] ? '<form method=POST><input class=lbut type=submit value=" '+price[e][0]+' Изумруд (10 суток) "><input type=hidden name="prem" value="1"><input type=hidden name="premium" value="'+e+'"><input type=hidden name="vcode" value="'+scod+'"><input type=hidden name="post_id" value="66"></form>' : '<input class=lbut type=button value=" '+price[e][0]+' Изумруд (10 суток) " disabled><br>') : '' );
	buy +=  ( price[e][1] > 0 ? (dlr >= price[e][1] ? '<form method=POST><input class=lbut type=submit value=" '+price[e][1]+' Изумруд (30 суток) "><input type=hidden name="prem" value="2"><input type=hidden name="premium" value="'+e+'"><input type=hidden name="vcode" value="'+scod+'"><input type=hidden name="post_id" value="66"></form>' : '<input class=lbut type=button value=" '+price[e][1]+' Изумруд (30 суток) " disabled><br>') : '' );
	buy +=  ( price[e][2] > 0 ? (dlr >= price[e][2] ? '<form method=POST><input class=lbut type=submit value=" '+price[e][2]+' Изумруд (60 суток) "><input type=hidden name="prem" value="3"><input type=hidden name="premium" value="'+e+'"><input type=hidden name="vcode" value="'+scod+'"><input type=hidden name="post_id" value="66"></form>' : '<input class=lbut type=button value=" '+price[e][2]+' Изумруд (60 суток) " disabled><br>') : '' );
	buy +=  ( price[e][3] > 0 ? (dlr >= price[e][3] ? '<form method=POST><input class=lbut type=submit value=" '+price[e][3]+' Изумруд (90 суток) "><input type=hidden name="prem" value="4"><input type=hidden name="premium" value="'+e+'"><input type=hidden name="vcode" value="'+scod+'"><input type=hidden name="post_id" value="66"></form>' : '<input class=lbut type=button value=" '+price[e][3]+' Изумруд (90 суток) " disabled><br>') : '' );
	param = 'Масса рюкзака: <b>+'+premium[e][1]+'</b><br>Множитель опыта: <b>х'+premium[e][2]+'</b><br>Расширенный дроп из ботов: <b>+/- '+premium[e][3]+'ур.</b><br>Максиальный опыт за бой: <b>'+premium[e][4]+'</b><br>Бонус опыта в пвп: <b>x'+premium[e][5]+'</b><br>Бонус опыта за бои между склонностями: <b>x'+premium[e][6]+'</b><br>Доп.возможности: <b>'+priv[premium[e][7]]+'</b><br>Сейф в банке: <b>'+seif[premium[e][8]]+'</b><br>Встроенный автобой для браузеров: <b>'+auto[premium[e][9]]+'</b><br>Расширенные смайлы на форуме: <b>'+smiles[premium[e][10]]+'</b>';
	table = '<fieldset><LEGEND align=center><font class="freemain"><font color="#3564A5"><b>Аккаунт '+names[e]+'</b></font></font></LEGEND><table cellpadding="5" cellspacing="0" border="0" width="100%" bgcolor=#EEEEEE><tr><td><img src="/img/image/NewDesign/premium/'+img[e]+'"></td><td valign="middle" class="nickname" width="100%">'+param+'<br><br>'+(e > 0 ? '<b>&nbsp;&nbsp;Купить:</b><br>'+buy : '<b>Активен у всех новых игроков, так же автоматически становится активным при окончании других типов аккаунтов.</b>' )+'</td></tr></table></fieldset>';
	el.innerHTML = table;
}

writeinfo_lr = function(e){
	el = d.getElementById('prem_info');
	buy = ( price[e][0] > 0 ? (lr >= price[e][0] ? '<form method=POST><input class=lbut type=submit value=" '+price[e][0]+' монет (10 суток) "><input type=hidden name="prem" value="1"><input type=hidden name="premium" value="'+e+'"><input type=hidden name="vcode" value="'+scod+'"><input type=hidden name="post_id" value="66"></form>' : '<input class=lbut type=button value=" '+price[e][0]+' Монет (10 суток) " disabled><br>') : '' );
	buy +=  ( price[e][1] > 0 ? (lr >= price[e][1] ? '<form method=POST><input class=lbut type=submit value=" '+price[e][1]+' монет (30 суток) "><input type=hidden name="prem" value="2"><input type=hidden name="premium" value="'+e+'"><input type=hidden name="vcode" value="'+scod+'"><input type=hidden name="post_id" value="66"></form>' : '<input class=lbut type=button value=" '+price[e][1]+' Монет (30 суток) " disabled><br>') : '' );
	buy +=  ( price[e][2] > 0 ? (lr >= price[e][2] ? '<form method=POST><input class=lbut type=submit value=" '+price[e][2]+' монет (60 суток) "><input type=hidden name="prem" value="3"><input type=hidden name="premium" value="'+e+'"><input type=hidden name="vcode" value="'+scod+'"><input type=hidden name="post_id" value="66"></form>' : '<input class=lbut type=button value=" '+price[e][2]+' Монет (60 суток) " disabled><br>') : '' );
	buy +=  ( price[e][3] > 0 ? (lr >= price[e][3] ? '<form method=POST><input class=lbut type=submit value=" '+price[e][3]+' монет (90 суток) "><input type=hidden name="prem" value="4"><input type=hidden name="premium" value="'+e+'"><input type=hidden name="vcode" value="'+scod+'"><input type=hidden name="post_id" value="66"></form>' : '<input class=lbut type=button value=" '+price[e][3]+' Монет (90 суток) " disabled><br>') : '' );
	param = 'Масса рюкзака: <b>+'+premium[e][1]+'</b><br>Множитель опыта: <b>х'+premium[e][2]+'</b><br>Расширенный дроп из ботов: <b>+/- '+premium[e][3]+'ур.</b><br>Максиальный опыт за бой: <b>'+premium[e][4]+'</b><br>Бонус опыта в пвп: <b>x'+premium[e][5]+'</b><br>Бонус опыта за бои между склонностями: <b>x'+premium[e][6]+'</b><br>Доп.возможности: <b>'+priv[premium[e][7]]+'</b><br>Сейф в банке: <b>'+seif[premium[e][8]]+'</b><br>Встроенный автобой для браузеров: <b>'+auto[premium[e][9]]+'</b><br>Расширенные смайлы на форуме: <b>'+smiles[premium[e][10]]+'</b>';
	table = '<fieldset><LEGEND align=center><font class="freemain"><font color="#3564A5"><b>Аккаунт '+names[e]+'</b></font></font></LEGEND><table cellpadding="5" cellspacing="0" border="0" width="100%" bgcolor=#EEEEEE><tr><td><img src="/img/image/NewDesign/premium/'+img[e]+'"></td><td valign="middle" class="nickname" width="100%">'+param+'<br><br>'+(e > 0 ? '<b>&nbsp;&nbsp;Купить:</b><br>'+buy : '<b>Активен у всех новых игроков, так же автоматически становится активным при окончании других типов аккаунтов.</b>' )+'</td></tr></table></fieldset>';
	el.innerHTML = table;
}