<?
	include($_SERVER["DOCUMENT_ROOT"]."/inc/pers/exp.php");
	include($_SERVER["DOCUMENT_ROOT"]."/inc/pers/modif.php");
	include($_SERVER["DOCUMENT_ROOT"]."/inc/pers/clan_bonus.php");
?>
<div></div>
<?
	include($_SERVER["DOCUMENT_ROOT"]."/inc/pers/mag.php");
	include($_SERVER["DOCUMENT_ROOT"]."/inc/pers/prof.php");
?>