$ = function(id){
	return document.getElementById(id);
}

ErrorStr = function(id){
	if($(id).style.display == 'none'){
		$(id).style.display = 'block';
	}else if($(id).style.display == 'block'){
		$(id).style.display = 'none';
	}
}

document.write('<div id="lavka" style="display:none;"><table cellspacing="0" cellpadding="0" width="300" style="position:relative;width:300px; top:150px; margin:0 auto;">  <tr>    <td style="width:18px;height:18px;"><div style="position:absolute; width:30px; height:30px; background:url(http://img.legendbattles.ru/image/closebox.png) no-repeat;right:0px;top:0px;cursor:pointer;" onclick="ErrorStr(\'lavka\');">&nbsp;</div><img src="http://img.legendbattles.ru/image/FormUp/left_parent.png" width="18" height="18"></td>    <td style="height:18px;background-image:url(\'http://img.legendbattles.ru/image/FormUp/parent.png\');"></td>    <td style="width:18px;height:18px;"><img src="http://img.legendbattles.ru/image/FormUp/right_parent.png" width="18" height="18"></td>  </tr>  <tr>    <td style="width:18px;background-image:url(\'http://img.legendbattles.ru/image/FormUp/left.png\');"></td>    <td style="background-image:url(\'http://img.legendbattles.ru/image/FormUp/bg.png\');" align="center"><font class=nickname style="color:black;border:1px;"><b>Вход только с 5 уровня!</b></font></td>    <td style="width:18px;background-image:url(\'http://img.legendbattles.ru/image/FormUp/right.png\');"></td>  </tr>  <tr>    <td style="width:18px;height:18px;"><img src="http://img.legendbattles.ru/image/FormUp/left_bottom.png" width="18" height="18"></td>    <td style="height:18px;background-image:url(\'http://img.legendbattles.ru/image/FormUp/bottom.png\');"></td>    <td style="width:18px;height:18px;"><img src="http://img.legendbattles.ru/image/FormUp/right_bottom.png" width="18" height="18"></td>  </tr></table></div>');

document.write('<div id="zakon" style="display:none;"><table cellspacing="0" cellpadding="0" width="300" style="position:relative;width:300px; top:150px; margin:0 auto;">  <tr>    <td style="width:18px;height:18px;"><div style="position:absolute; width:30px; height:30px; background:url(http://img.legendbattles.ru/image/closebox.png) no-repeat;right:0px;top:0px;cursor:pointer;" onclick="ErrorStr(\'zakon\');">&nbsp;</div><img src="http://img.legendbattles.ru/image/FormUp/left_parent.png" width="18" height="18"></td>    <td style="height:18px;background-image:url(\'http://img.legendbattles.ru/image/FormUp/parent.png\');"></td>    <td style="width:18px;height:18px;"><img src="http://img.legendbattles.ru/image/FormUp/right_parent.png" width="18" height="18"></td>  </tr>  <tr>    <td style="width:18px;background-image:url(\'http://img.legendbattles.ru/image/FormUp/left.png\');"></td>    <td style="background-image:url(\'http://img.legendbattles.ru/image/FormUp/bg.png\');" align="center"><font class=nickname style="color:black;border:1px;"><b>Вход запрещен!</b></font></td>    <td style="width:18px;background-image:url(\'http://img.legendbattles.ru/image/FormUp/right.png\');"></td>  </tr>  <tr>    <td style="width:18px;height:18px;"><img src="http://img.legendbattles.ru/image/FormUp/left_bottom.png" width="18" height="18"></td>    <td style="height:18px;background-image:url(\'http://img.legendbattles.ru/image/FormUp/bottom.png\');"></td>    <td style="width:18px;height:18px;"><img src="http://img.legendbattles.ru/image/FormUp/right_bottom.png" width="18" height="18"></td>  </tr></table></div>');

document.write('<div id="master" style="display:none;"><table cellspacing="0" cellpadding="0" width="300" style="position:relative;width:300px; top:150px; margin:0 auto;">  <tr>    <td style="width:18px;height:18px;"><div style="position:absolute; width:30px; height:30px; background:url(http://img.legendbattles.ru/image/closebox.png) no-repeat;right:0px;top:0px;cursor:pointer;" onclick="ErrorStr(\'master\');">&nbsp;</div><img src="http://img.legendbattles.ru/image/FormUp/left_parent.png" width="18" height="18"></td>    <td style="height:18px;background-image:url(\'http://img.legendbattles.ru/image/FormUp/parent.png\');"></td>    <td style="width:18px;height:18px;"><img src="http://img.legendbattles.ru/image/FormUp/right_parent.png" width="18" height="18"></td>  </tr>  <tr>    <td style="width:18px;background-image:url(\'http://img.legendbattles.ru/image/FormUp/left.png\');"></td>    <td style="background-image:url(\'http://img.legendbattles.ru/image/FormUp/bg.png\');" align="center"><font class=nickname style="color:black;border:1px;"><b>В данное время вход в мастерскую возможен с 5 уровня!</b></font></td>    <td style="width:18px;background-image:url(\'http://img.legendbattles.ru/image/FormUp/right.png\');"></td>  </tr>  <tr>    <td style="width:18px;height:18px;"><img src="http://img.legendbattles.ru/image/FormUp/left_bottom.png" width="18" height="18"></td>    <td style="height:18px;background-image:url(\'http://img.legendbattles.ru/image/FormUp/bottom.png\');"></td>    <td style="width:18px;height:18px;"><img src="http://img.legendbattles.ru/image/FormUp/right_bottom.png" width="18" height="18"></td>  </tr></table></div>');

document.write('<div id="arena" style="display:none;"><table cellspacing="0" cellpadding="0" width="300" style="position:relative;width:300px; top:150px; margin:0 auto;">  <tr>    <td style="width:18px;height:18px;"><div style="position:absolute; width:30px; height:30px; background:url(http://img.legendbattles.ru/image/closebox.png) no-repeat;right:0px;top:0px;cursor:pointer;" onclick="ErrorStr(\'arena\');">&nbsp;</div><img src="http://img.legendbattles.ru/image/FormUp/left_parent.png" width="18" height="18"></td>    <td style="height:18px;background-image:url(\'http://img.legendbattles.ru/image/FormUp/parent.png\');"></td>    <td style="width:18px;height:18px;"><img src="http://img.legendbattles.ru/image/FormUp/right_parent.png" width="18" height="18"></td>  </tr>  <tr>    <td style="width:18px;background-image:url(\'http://img.legendbattles.ru/image/FormUp/left.png\');"></td>    <td style="background-image:url(\'http://img.legendbattles.ru/image/FormUp/bg.png\');" align="center"><font class=nickname style="color:black;border:1px;"><b>Арена на реконструкции!</b></font></td>    <td style="width:18px;background-image:url(\'http://img.legendbattles.ru/image/FormUp/right.png\');"></td>  </tr>  <tr>    <td style="width:18px;height:18px;"><img src="http://img.legendbattles.ru/image/FormUp/left_bottom.png" width="18" height="18"></td>    <td style="height:18px;background-image:url(\'http://img.legendbattles.ru/image/FormUp/bottom.png\');"></td>    <td style="width:18px;height:18px;"><img src="http://img.legendbattles.ru/image/FormUp/right_bottom.png" width="18" height="18"></td>  </tr></table></div>');

document.write('<div id="CityOut" style="display:none;"><table cellspacing="0" cellpadding="0" width="300" style="position:relative;width:300px; top:150px; margin:0 auto;">  <tr>    <td style="width:18px;height:18px;"><div style="position:absolute; width:30px; height:30px; background:url(http://img.legendbattles.ru/image/closebox.png) no-repeat;right:0px;top:0px;cursor:pointer;" onclick="ErrorStr(\'CityOut\');">&nbsp;</div><img src="http://img.legendbattles.ru/image/FormUp/left_parent.png" width="18" height="18"></td>    <td style="height:18px;background-image:url(\'http://img.legendbattles.ru/image/FormUp/parent.png\');"></td>    <td style="width:18px;height:18px;"><img src="http://img.legendbattles.ru/image/FormUp/right_parent.png" width="18" height="18"></td>  </tr>  <tr>    <td style="width:18px;background-image:url(\'http://img.legendbattles.ru/image/FormUp/left.png\');"></td>    <td style="background-image:url(\'http://img.legendbattles.ru/image/FormUp/bg.png\');" align="center"><font class=nickname style="color:black;border:1px;"><b>Выход воспрещён, ожидайте утра.</b></font></td>    <td style="width:18px;background-image:url(\'http://img.legendbattles.ru/image/FormUp/right.png\');"></td>  </tr>  <tr>    <td style="width:18px;height:18px;"><img src="http://img.legendbattles.ru/image/FormUp/left_bottom.png" width="18" height="18"></td>    <td style="height:18px;background-image:url(\'http://img.legendbattles.ru/image/FormUp/bottom.png\');"></td>    <td style="width:18px;height:18px;"><img src="http://img.legendbattles.ru/image/FormUp/right_bottom.png" width="18" height="18"></td>  </tr></table></div>');